language: php

php:
  - '7.2'
  - '7.3'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-lowest --prefer-source --no-interaction

script: phpunit

notifications:
    on_success: never
    on_failure: always